# Generated by Django 5.0 on 2023-12-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subject')),
                ('user_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.class')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.classsubject'),
        ),
    ]
