# Generated by Django 5.0 on 2023-12-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_subject_name_classsubject_teacher_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.student'),
        ),
    ]
