# Generated by Django 5.0 on 2023-12-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_session_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
    ]
