# Generated by Django 5.0 on 2024-01-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_mark_marks_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.mark'),
        ),
    ]
