# Generated by Django 5.0 on 2024-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_student_exam_remove_student_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
