# Generated by Django 5.0 on 2024-01-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_mark_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
