# Generated by Django 5.0 on 2024-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_mark_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
