# Generated by Django 5.0 on 2024-01-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_remove_mark_grade_remove_mark_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacher',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='selection',
        ),
        migrations.AddField(
            model_name='classteacher',
            name='selection',
            field=models.ManyToManyField(null=True, to='portal.classsubject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='selection',
            field=models.ManyToManyField(null=True, to='portal.classsubject'),
        ),
    ]
